#!/usr/bin/env python3
"""
extract_deps.py — Produces deps.json for the Reversa Docs Team.

Wave 1 skeleton. Real import analysis per language comes in TASK-07.

Output schema: see specs/reversa-docs/design.md, section "deps.json Schema".

Usage:
    python extract_deps.py --modules _reversa_docs/assets/data/modules.json \
                           --out _reversa_docs/assets/data/deps.json
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except AttributeError:
        pass


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--modules", required=True,
                        help="Path to modules.json generated by extract_modules.py")
    parser.add_argument("--out", required=True, help="Output path for deps.json")
    args = parser.parse_args()

    modules_data = json.loads(Path(args.modules).read_text(encoding="utf-8"))
    nodes = [{"id": m["id"]} for m in modules_data.get("modules", [])]

    # Real import analysis in TASK-07. For now just empty nodes + empty edges.
    out = {
        "schemaVersion": 1,
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "nodes": nodes,
        "edges": [],
        "cycles": [],
    }

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"OK (skeleton): {len(nodes)} nodes, 0 edges in {out_path}")


if __name__ == "__main__":
    main()
